### ISSUE TITLE
eslint not finding it's config file

### ISSUE THREAD

**Issue by schickm** [Delapouite/eslint-formatter-kakoune#1]
When I tried to implement the hook, eslint errored out complaining that it couldn't find the associated `.eslintrc.js` file.  Here's the output I receive if I run the command generated from `lint.kak`:
```
eslint --format=node_modules/eslint-formatter-kakoune  /var/folders/gl/8s66xz851z7f1f9_yh8w5y980000gn/T//kak-lint.IOiskgm5'/buf.js'

Oops! Something went wrong! :(

ESLint: 5.6.0.
ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /private/var/folders/gl/8s66xz851z7f1f9_yh8w5y980000gn/T/kak-lint.IOiskgm5 and its ancestors. If it found none, it then looked in your home directory.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

Because of mawww/kakoune#2302  you have no idea that your linter is actually failing, and it just reports to have no linting errors.

In order to fix this, I added the `--config .eslintrc.js` flag to point it back to the config in the current working directory.  This is working for me, seems like you might want to modify the documentation for this plugin to include this:

```
hook global WinSetOption filetype=javascript %{
  set buffer lintcmd 'eslint --config .eslintrc.js --format=node_modules/eslint-formatter-kakoune'
  lint-enable
  lint
}
```

**Comment by Delapouite** [comment]
Thanks for the explanation and sorry about the delay. It's merged.
