### ISSUE TITLE
Mention `eslint --format unix` as alternative?

### ISSUE THREAD

**Issue by jssee** [Delapouite/eslint-formatter-kakoune#5]
Its seems somewhere along the way, `eslint` started shipping a `unix` option for the output format that kakoune can digest and output to the lint buffer. I still think this package might be useful if you're using an older version of eslint or if you don't like the `unix` format, but I think it might be useful to mention this as an alternative?

this is how the output appears in the `*lint-ouput*` buffer
```
dist/index.js:9:5: 'foo' is never reassigned. Use 'const' instead. [Error/prefer-const]
```

**Comment by Delapouite** [comment]
Hello.

It looks like that the `unix` formatter is from 2015, which predates this kakoune plugin: https://github.com/eslint/eslint/commit/bfaaac5f160bb86b83781afa7b524bee8b28fde7

I don't remember exactly, but I think I had evaluated this unix formatter before starting this plugin and it didn't exactly fit the format used by `lint.kak`. Is this assumption still correct?

**Comment by jssee** [comment]
Hi.

The only obvious difference I can see is that it doesnt print `Kind` after the error position and since it still outputs a `Total` error count at the end so the `*lint-output*` buffer has a couple extra blank lines at the end.  but even with these discrepancies you can still jump to the error locations from the lint buffer.

is there some other functionality i should test?
